spring:
  profiles:
    active: local
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  datasource:
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED

gtm.data.set: gtm_log_dev
logging:
  config: classpath:logback-spring.xml