spring:
  profiles:
    active: local

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create

  datasource:
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED

---

spring:
  profiles: local
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true